### ISSUE TITLE
UPM config on Windows runners

### ISSUE THREAD

**Issue by lukas-prodviz** [game-ci/unity-builder#618]
Hello,

According to the documentation, UPM authentication on Ubuntu is configured by creating the upmconfig file under `/home/runner/work/_temp/_github_home`.

In which directory should this file be placed on Windows runners?

I already tried to use `$HOME` and change the Ubuntu example from the documentation as follows:

      - name: Create .upmconfig.toml UPM authentication file
        env:
          npm_token: ${{ secrets.NPM_TOKEN }}
        run: |
          cd $HOME
          echo "[npmAuth.`"https://upm.example.com`"]" > .upmconfig.toml
          echo "_auth = `"$Env:npm_token`"" >> .upmconfig.toml
          echo "alwaysAuth = true" >> .upmconfig.toml

But this still gives me the message "... failed because it lacks valid authentication credentials" when the package manager tries to resolve the dependencies, whereas on Ubuntu everything works as expected.

**Comment by GabLeRoux** [comment]
I think this could be related:
https://github.com/game-ci/unity-test-runner/pull/261

It's not for the builder project, but it does work with the .upmconfig.toml. We might need to do similar logic for the builder project.

**Comment by nvandessel** [comment]
Unfortunately for the test-runner, package-mode has the caveat of only working on Linux runners due to the dependency on `jq`, issue being tracked here: https://github.com/game-ci/unity-test-runner/issues/224

So that means that I haven't been able to confirm it working on a Windows machine.

One possible option is to try a different location for the toml that is accepted by Unity. See valid locations [here](https://docs.unity3d.com/Manual/upm-config.html#upmconfigUser).
So instead of: `cd $HOME`, it might be: `cd C:\ProgramData\Unity\config\`

**Comment by laurentinosn-chimera** [comment]
@lukas-prodviz have you managed to work with this config? I'm having the same issue. I'm also trying to build on a self-hosted Windows agent and must authenticate it with my external package manager. I have tried using various approaches without success:
Creating the upm file to C:\ProgramData\Unity\config\;
Try creating on  `${{ runner.temp }}/_github_home`
And finally using this:

 ```
     - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          ...
          UPM_REGISTRY_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          ...
          scopedRegistryUrl: http://myserver.upm.com:8080

```
Still looking to solve this problem =/

**Comment by Shaun-Fong** [comment]
> @lukas-prodviz have you managed to work with this config? I'm having the same issue. I'm also trying to build on a self-hosted Windows agent and must authenticate it with my external package manager. I have tried using various approaches without success: Creating the upm file to C:\ProgramData\Unity\config; Try creating on `${{ runner.temp }}/_github_home` And finally using this:
> 

You cannot use `scopedRegistryUrl` as an input parameter because it does not exist in the builder at all.

> ```
>     - name: Build project
>        uses: game-ci/unity-builder@v4
>        env:
>          ...
>          UPM_REGISTRY_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
>        with:
>          ...
>          scopedRegistryUrl: http://myserver.upm.com:8080
> ```
Try PR #665; it should work with your actions.
I successfully set up GitHub Packages as a private registry in my private repo.

**Comment by laurentinosn-chimera** [comment]
It worked, thank @Shaun-Fong

**Comment by davidmfinol** [comment]
Looks like this is resolved, so closing this issue.

**Comment by lukas-prodviz** [comment]
PR #665 has never been merged - so the issue unfortunately still exists.

**Comment by nobnak** [comment]
The correct location for the UPM configuration file (.upmconfig.toml) on Windows runner is "`D:\a\_temp\_github_home\.upmconfig.toml`".

**Comment by davidmfinol** [comment]
Re-opening this issue if some-one wants to resubmit a PR
